config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'pages/about'
  get 'about',to: 'pages#about'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord 
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner
  has_rich_text :body
  # rằng buộc 
  validates :title, length: { minimum: 5 }

  validates :body,  length: { minimum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin!

    private
    def is_admin!
        if current_user && current_user.admin
        else
            redirect_to root_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:index, :show]
  # GET /posts or /posts.json

  def index
    @posts = Post.order(views: :desc)
  end
  
  # GET /posts/1 or /posts/1.json
  def show
    @post.views ||= 0
    @post.views += 1
    @post.save()
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end
  
  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %> ">Bài viết</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>" >Trang chủ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=  about_path  %>">Chúng tôi</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
         <% if current_user %>
            <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    <%= current_user.email %>
                </button>

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
                    <li><button class="dropdown-item" type="button"><a class="dropdown-item" href=" <%= edit_user_registration_path %>"> Tài khoản </a></button></li>
                    <% if current_user.admin %>
                    <li><button class="dropdown-item" type="button"><a class="dropdown-item" href=" <%= new_post_path %>"> Bài viết mới </a></button></li>
                    <% end %>
                    <li>
                    <button class="dropdown-item">
                     <%= link_to "Đăng xuất", destroy_user_session_path,class:'dropdown-item', method: :delete %>
                    </button>
                    </li>
                </ul>
         <% else %>
                    <li>
                    <%= link_to "Đăng ký", new_user_registration_path, class:'dropdown-item' %>
                    </li>
                    <li>
                    <%= link_to "Đăng Nhập", new_user_session_path, class:'dropdown-item' %>
                    </li>
        <% end %>
            </div>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>  </body>
</html>

app/views/pages/about.html.erb
<!-- inside app/views/welcome/index.html.erb -->  
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Nhóm 10: Ruby on Rails Blog</h1>
        <p class="lead text-muted">Blog này được tạo ra để chia sẻ những kiến thức về công nghệ thông tin đến mọi người. Vận dụng những kiến thức đã tìm hiểu về Ruby và Ruby on Rails nhóm 10 đã xây dựng Blog trên nền tảng Rails.<br>Nếu có bất kỳ thắc mắc hay góp ý nào hãy liên hệ với chúng tôi<p>
          <a href="mailto:codyhoang.it@gmail.com" class="btn btn-primary my-2">Liên hệ với chúng tôi</a>
          <a href="https://github.com/Cody-Hoang/myblog" class="btn btn-secondary my-2">Github</a>
        </p>
      </div>
    </div>
  </section>
</main>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  
  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>
        <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
      <% end %>
      
    <%= f.label "Ảnh trang chủ", class:'form-control' %>
    <%= f.file_field :thumbnail %>
            <% @post.errors.full_messages_for(:thumbnail).each do |message| %>
      <div><%= message %></div>
      <% end %>
    <%= f.label :banner, class:'form-control' %>
    <%= f.file_field :banner %>
                <% @post.errors.full_messages_for(:banner).each do |message| %>
      <div><%= message %></div>
      
      <% end %>
      
    <%= f.rich_text_area :body %>
        <% @post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , class:'btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Chỉnh sửa nội dung</h1>

<%= render 'form', post: @post %>

<%= link_to 'Xem', @post %> |
<%= link_to 'Quay lại', posts_path %>

app/views/posts/index.html.erb
<div class="w-75 container">
    <% @posts.each do |post| %>
    <div class="row">
        <div class="card mb-3">
        <% if post.thumbnail.blank? %>
        <% else %>
            <img class="card-img-top" src="<%= url_for post.thumbnail %>" alt="Ảnh" />
        <% end %>
        
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to post.title, post %>
                </h5>
                <p class="card-text">
                    <%= post.body.to_plain_text.truncate_words(100) %>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                    Cập nhật
                        <%= post.updated_at.strftime("%A, %B %e, %Y") %> bởi
                        <%= post.user.email %> | <%= post.views %> lượt xem | 0 bình luận
                        <% if current_user %>
                          <% if current_user.admin %>
                                  <%= link_to 'Sửa', edit_post_path(post) %>
                                  <%= link_to 'Xóa', post, method: :delete, data: { confirm: 'Bạn có chác muốn xóa ?' } %>
                          <% end %>
                        <% end %>
                        
                    </small>
                </p>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>Bài viết mới</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div style="width:100%; height: 300px; overflow-y:hidden">
        <% if @post.banner.blank? %>
        <% else %>
  <%= image_tag(@post.banner, style:'width:100%') %>

        <% end %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width:100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
       Tạo <%= @post.updated_at %> bởi <%= @post.user.email %> | <%= @post.views %> lượt xem
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>